<?php
namespace app\models;

use yii\db\ActiveRecord;

class Moderation extends ActiveRecord
{
    const SCENARIO_CREATE = 'create';

    public $tags;
    public $verifyCode;

    public static function tableName()
    {
        return 'moderation';
    }

    public function rules()
    {
        return [
            [['text', 'ip', 'user_agent'], 'filter', 'filter'=>'strip_tags'],
            [['ip', 'user_agent'], 'string', 'max' => 255],
            [['text'], 'string', 'min' => 4, 'max' => 65535],
            [['created'], 'date', 'format' => 'yyyy-M-d H:m:s'],
            [['created'], 'default', 'value' => date("Y-m-d H:i:s")],
            [['text', 'hash', 'created', 'ip', 'user_agent'], 'required'],
            ['verifyCode', 'captcha', 'on' => self::SCENARIO_CREATE],
        ];
    }

    public function attributeLabels()
    {
        return [
            'text' => 'Текст поста',
            'verifyCode' => 'Код с картинки',
        ];
    }

    public function beforeValidate()
    {
        if ($this->isNewRecord) {
            $this->created = date('Y-m-d H:i:s');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}