<?php
namespace app\models;

use yii\db\ActiveRecord;

class Post extends ActiveRecord
{
    public $tags;

    public static function tableName()
    {
        return 'post';
    }

    public function rules()
    {
        return [
            [['ip', 'user_agent',], 'string', 'max' => 255],
            [['text'], 'string', 'min' => 4, 'max' => 65535],
            [['created'], 'date', 'format' => 'yyyy-M-d H:m:s'],
            [['created'], 'default', 'value' => date("Y-m-d H:i:s")],
            [['text', 'tags', 'ip', 'user_agent', 'created',], 'required'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'text' => 'Текст',
            'tags' => 'Теги',
        ];
    }

    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
            ->viaTable('tag4post', ['post_id' => 'id']);
    }

    public function beforeValidate()
    {
        if ($this->isNewRecord) {
            $this->created = date('Y-m-d H:i:s');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}